// Tooling-level checks, run AFTER `npm run fixtures` (see package.json test
// script): budgets.json must be well-formed, and the fixture pipeline must
// produce the exact shapes the smoke test and the §8 budget enforce.
//
// Note: the port to the MBTA Viz exemplar architecture removed the old
// src/js/*-math.js helper modules and the ESM section loader, so the
// helper-level unit tests that imported them were dropped with them.
// Rendering code now lives in classic scripts ported from the exemplar and
// is verified at build/runtime time (see tools/build.js, smoke-test.js).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = join(ROOT, 'dist');
const HASH_RE = /^[a-f0-9]{8}$/;

function readJson(rel) {
  const p = join(ROOT, rel);
  assert.ok(existsSync(p), `expected ${rel} to exist (run npm run fixtures first)`);
  return JSON.parse(readFileSync(p, 'utf8'));
}

test('budgets.json is well-formed and coherent', () => {
  const b = readJson('budgets.json');
  assert.equal(typeof b.totalMaxBytes, 'number');
  assert.ok(b.totalMaxBytes > 0, 'totalMaxBytes must be positive');
  assert.equal(typeof b.firstVisitTargetBytes, 'number');
  assert.ok(Array.isArray(b.artifacts) && b.artifacts.length > 0, 'artifacts must be a non-empty array');
  for (const a of b.artifacts) {
    assert.equal(typeof a.match, 'string');
    assert.equal(typeof a.maxBytes, 'number');
    assert.ok(a.maxBytes > 0, `budget for ${a.match} must be positive`);
  }
});

test('delay.json is exactly 7 days × 96 buckets = 672', () => {
  const delay = readJson('data/delay.json');
  assert.equal(delay.length, 672, 'must have 7×96 = 672 buckets');
  const days = new Set(delay.map((b) => b.day));
  assert.deepEqual([...days].sort(), [0, 1, 2, 3, 4, 5, 6], 'all 7 days present');
  const seconds = delay.map((b) => b.secOfDay);
  assert.equal(new Set(seconds).size, 96, '96 unique 15-minute buckets per day');
  for (const b of delay) {
    assert.ok(b.ins && typeof b.ins === 'object' && !Array.isArray(b.ins), 'ins is a station map');
    assert.ok(b.outs && typeof b.outs === 'object' && !Array.isArray(b.outs), 'outs is a station map');
    assert.equal(typeof b.ins_total, 'number', 'ins_total is the numeric total');
  }
});

test('live.json has at least one train with position fields', () => {
  const live = readJson('data/live.json');
  assert.ok(Array.isArray(live.trains) && live.trains.length >= 1, 'at least 1 train');
  const t = live.trains[0];
  for (const key of ['train_id', 'lat', 'lon', 'lateness_min', 'origin', 'destination']) {
    assert.ok(key in t, `train record has ${key}`);
  }
});

test('marey trips are split per day+line with an index', () => {
  const idx = readJson('data/marey-index.json');
  assert.ok(idx.days.length >= 1);
  assert.ok(idx.lines.length >= 1);
  for (const day of idx.days) {
    for (const line of day.lines) {
      const f = `data/marey-trips-${day.date}-${line.line}.json`;
      const trips = readJson(f);
      assert.ok(Array.isArray(trips) && trips.length >= 1, `${f} non-empty`);
      for (const trip of trips) {
        assert.ok(trip.service && trip.line, 'trip has service and line');
        assert.ok(Array.isArray(trip.stops) && trip.stops.length >= 2, 'trip has ≥2 stops');
        assert.ok(trip.begin < trip.end, 'trip.begin < trip.end');
        assert.ok(trip.begin > 1e9, 'plausible epoch timestamp');
      }
    }
  }
});

test('index.html references only assets that exist in src/', () => {
  const html = readFileSync(join(ROOT, 'src/index.html'), 'utf8');
  const refs = [...html.matchAll(/(?:href|src)="([^"]+)"/g)].map((m) => m[1]);
  assert.ok(refs.length >= 2, 'page references at least css + js');
  for (const ref of refs) {
    if (ref.startsWith('http') || ref.startsWith('#')) continue; // external/fragment links allowed
    if (ref === 'assets/js/files.js') continue; // generated by tools/build.js into dist
    const stripped = join(ROOT, 'src', ref.replace(/^assets\//, ''));
    const raw = join(ROOT, 'src', ref);
    assert.ok(existsSync(stripped) || existsSync(raw), `referenced file exists in src/: ${ref}`);
  }
});

test('build hashes assets and index.html references the hashed names', () => {
  assert.ok(existsSync(join(DIST, 'index.html')), 'dist/index.html missing');
  const html = readFileSync(join(DIST, 'index.html'), 'utf8');
  const refs = [...html.matchAll(/(?:src|href)="(assets\/[^"]+)"/g)].map((m) => m[1]);
  assert.ok(refs.length > 0, 'expected asset references in dist/index.html');
  for (const ref of refs) {
    const parts = ref.split('/');
    const file = parts.at(-1);
    const stem = file.replace(/\.(js|css|svg|png|ico)$/, ''); // strip extension (vendor files have multi-dot stems, e.g. moment.min)
    const base = stem.split('.').slice(0, -1).join('.');
    const hash = stem.split('.').at(-1);
    assert.match(hash, HASH_RE, `${ref} has no 8-hex content hash`);
    assert.ok(existsSync(join(DIST, ...parts)), `${ref} missing from dist`);
    // same basename must not appear un-hashed anywhere in dist/index.html
    assert.ok(!html.includes(`${base}.js`) && !html.includes(`${base}.css`),
      `un-hashed reference to ${base} remains`);
  }
});

test('dist has a files.js with sizes+hashes for every data json', () => {
  const distAssets = readFileSync(join(DIST, 'index.html'), 'utf8');
  const filesJsRef = [...distAssets.matchAll(/(?:src)="(assets\/js\/files\.[a-f0-9]{8}\.js)"/g)].map((m) => m[1]);
  assert.equal(filesJsRef.length, 1, 'dist/index.html references the hashed files.js exactly once');
  const filesJs = readFileSync(join(DIST, ...filesJsRef[0].split('/')), 'utf8');
  assert.match(filesJs, /VIZ\.fileSizes\s*=/, 'files.js defines VIZ.fileSizes');
  assert.match(filesJs, /VIZ\.fileHashes\s*=/, 'files.js defines VIZ.fileHashes');
  for (const f of ['data/network.json', 'data/delay.json', 'data/marey-index.json', 'data/live.json']) {
    assert.ok(filesJs.includes(`"${f}"`), `files.js covers ${f}`);
  }
});
